spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/noteTaking
    username: postgres
    password: md2s39kk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
